name: grablog
description: GrabLog
publish_to: 'none'
version: 0.2.0+3

environment:
  flutter: ^3.32.2
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  args: 2.7.0
  collection: any
  crypto: 3.0.6
  csv: 6.0.0
  data_table_2: 2.6.0
  file_selector: 1.0.3
  flutter_html: 3.0.0
  flutter_riverpod: 2.6.1
  freezed_annotation: 3.0.0
  html: 0.15.6
  http: 1.4.0
  intl: any
  logger: 2.5.0
  markdown_widget: 2.3.2+8
  package_info_plus: 8.3.0
  path: 1.9.1
  path_provider: 2.1.5
  pub_semver: 2.2.0
  riverpod_annotation: 2.6.1
  shared_preferences: 2.5.3
  toml: 0.16.0
  url_launcher: 6.3.1
  window_manager: 0.5.0
  yaml: 3.1.3

dev_dependencies:
  build_runner: 2.4.15
  custom_lint: 0.7.5
  flutter_lints: 6.0.0
  freezed: 3.0.6
  riverpod_generator: 2.6.5
  riverpod_lint: 2.6.5

flutter:
  uses-material-design: true
