name: grablog
description: GrabLog
publish_to: 'none'
version: 0.2.0+3

environment:
  flutter: ^3.38.3
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  args: 2.7.0
  collection: any
  crypto: 3.0.7
  csv: 6.0.0
  data_table_2: 2.7.2
  file_selector: 1.1.0
  flutter_html: 3.0.0
  flutter_riverpod: 3.0.3
  freezed_annotation: 3.1.0
  html: 0.15.6
  http: 1.6.0
  intl: any
  logger: 2.6.2
  markdown_widget: 2.3.2+8
  package_info_plus: 9.0.0
  path: 1.9.1
  path_provider: 2.1.5
  pub_semver: 2.2.0
  riverpod_annotation: 3.0.3
  shared_preferences: 2.5.4
  toml: 0.17.0
  url_launcher: 6.3.2
  window_manager: 0.5.1
  yaml: 3.1.3

dev_dependencies:
  build_runner: 2.10.4
  custom_lint: 0.8.1
  flutter_lints: 6.0.0
  freezed: 3.2.3
  riverpod_generator: 3.0.3
  riverpod_lint: 3.0.3

flutter:
  uses-material-design: true
